### ISSUE TITLE
Create 1099-MISC example over HTTP

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/irs#43]
It would be really helpful for the project to have an example of creating a 1099-MISC file over the HTTP service. This will better explain what's involved from a user of the IRS project. 

Included / linked on `docs/RUNNING.md` and the README.

**Comment by adamdecaf** [comment]
@mfdeveloper508 can you add this to your queue?

**Comment by mfdeveloper508** [comment]
sure, I will fix  the issue in next step

**Comment by mfdeveloper508** [comment]
added example file in running tab of docs/RUNNING.md
