### ISSUE TITLE
api: include example values in schemas

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/irs#47]
Recently I setup this project to serve API docs from GitHub Pages. This means we have a pretty view of API endpoints, however the examples aren't fully displayed. This is because there are no example values for the viewer to include.

Example values also help to show what to provide when making requests for people who are new to the 1099 files. 

See: https://moov-io.github.io/irs/api/

**Comment by adamdecaf** [comment]
@mfdeveloper508 can you add this to your work?

**Comment by mfdeveloper508** [comment]
sure, I will fix  the issue in next step

**Comment by mfdeveloper508** [comment]
added example file with 1099 form, we can view the example through swagger view.
